#!/usr/bin/perl
#
#########################################
#
# networkは/24の者のみをターゲットとする
#
#########################################

#
# 第３オクテットまでを指定する
# 後ろに必ず.をつけること
#
$tnw='192.168.12.';
while(1){
  $st = time();

  for($i=1;$i<255;$i++){
    if(system("ping -c 1 $tnw$i >& /dev/null ")<1){
      print "$tnw$i is up\n";
    }
  }

  $slpt = $st + 300 - time();
  if( $slpt > 0 ){ sleep($slpt); }
}
